### ISSUE TITLE
Update Azure samples to latest V6 and transports

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#1014] opened 2016-01-07 08:30 UTC
Based on @mat-mcloughlin list

- [x] azure\azure-service-bus
- [x] azure\blob-storage-databus
- [x] azure\native-integration-asb
- [x] azure\polymorphic-events-asb
- [ ] azure\shared-host
- [x] azure\storage-persistence
- [x] azure\storage-queues

@Particular/tf-async-transport ping

**Comment by SeanFeldman** [comment] 2016-01-07 18:24
Changing items into tasks to be able to see the progress on a higher (issues) level

**Comment by SimonCropp** [comment] 2016-04-05 12:19
duplicate of https://github.com/Particular/docs.particular.net/issues/804

**Closed by SimonCropp** 2016-04-05 12:19 UTC
Labels: Project: V6 Launch
