### ISSUE TITLE
Authoring a custom persistence

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#757] opened 2015-08-17 16:15 UTC
Connects to https://github.com/Particular/PlatformDevelopment/issues/682.

(Authoring a custom persistence](http://docs.particular.net/nservicebus/persistence/authoring-custom) needs an update for V6, since all the interfaces mentioned are breaking. Then the relevant parts of the v5 to v6 upgrade guide should link to this page as well as stating what changed.

Related: #744 #745 #746

@SimonCropp please advise on best way to express this since currently interfaces shown are just in Markdown, not snippets. As I said in (merged) PR:

> Simon, right now the interfaces (that are breaking) are rendered by Markdown. Would you recommend moving that to snippets, and then in the V6 snippet showing more than one interface in that snippet? Or some other way?

**Comment by SimonCropp** [comment] 2015-08-17 19:26
i have never liked that page. it has so many words and so little actual "helping me write a persistence"

**Comment by DavidBoike** [comment] 2015-08-17 19:33
Looking at it closer, you're totally right. There's little more here than a sloppily narrated form of what you'd get from dotPeek.

What do you think we should do with it? We could get rid of it. Custom persistence isn't exactly a common thing for a customer to do.

From your comment on the previous PRs on the upgrade guide that they should link _somewhere_, this seems like the logical spot, but how to do custom persistence is actually a very deeeeeeeep topic.

**Comment by SimonCropp** [comment] 2015-08-24 03:02
i think a sample that does a simple file based persistence would be beneficial

**Comment by indualagarsamy** [comment] 2016-03-17 21:37
@SimonCropp @DavidBoike - Should we simply deprecate the existing page, by adding a note to the article that it's only relevant for Versions 5 and below? While we decide on what the best approach is?

**Comment by DavidBoike** [comment] 2016-03-17 21:40
It's hardly even relevant for V5. Does it provide *any* real value? Should we just remove it?

There are so many things to think about when implementing a persistence.

I'm forced to disagree with the `Project: V6 Launch` label. Anyone who has successfully created persistence for V5 won't need this article to update to V6. And making that possible, while a nice to have, is not absolutely required to launch V6, in my opinion.

**Comment by SimonCropp** [comment] 2016-03-18 00:10
so the current article http://docs.particular.net/nservicebus/persistence/authoring-custom is so poor to the point of being useless. if we dont want to improve it and update for v6 we should delete the page.

if we keep it it has to be patched for v6

**Comment by weralabaj** [comment] 2016-03-18 08:55
I'm +1 for removing it now and creating a new issue to come up with a proper guidance.
The question I have though is how should we approach community persistences and transports? Should we create an upgrade doco for them or rather contact directly and collaborate to guide them through upgrade?
Then when should we do it? Before V6 beta/release? Right after?

**Comment by DavidBoike** [comment] 2016-03-18 14:04
@weralabaj:

> The question I have though is how should we approach community persistences and transports? Should we create an upgrade doco for them or rather contact directly and collaborate to guide them through upgrade?

Fantastic question. I raised Particular/PlatformDevelopment#682 it as an issue for the PlatDev V6 Launch task force to tackle.

@SimonCropp: I don't want to keep this. What's the best way to "delete" it? Just delete the file, and then it 404s? Or should something else be done? And then, should we leave a backout commit in another branch and link it to this issue?

**Comment by weralabaj** [comment] 2016-03-23 08:08
@SimonCropp @DavidBoike Given that creating a high-quality content on that issue requires non-trivial amount of effort, how about leaving the doco for now, closing this issue and dealing with https://github.com/Particular/PlatformDevelopment/issues/682, which is the most important aspect for now?

I've used the doco to tell customers how to fix the timeout issue, so it's not completely useless.

**Comment by SimonCropp** [comment] 2016-03-23 08:21
@weralabaj the problem is leaving it there, as is, in the context of V6

**Comment by weralabaj** [comment] 2016-03-23 08:27
So should we just delete it? I don't see other options at the moment.

**Comment by weralabaj** [comment] 2016-03-25 10:27
Issue related to https://github.com/Particular/PlatformDevelopment/issues/682.

**Comment by weralabaj** [comment] 2016-03-31 10:31
Issue related to Particular/PlatformDevelopment#682. We'll tackle it there, once it gets prioritized by the squad.

**Closed by weralabaj** 2016-03-31 10:31 UTC
Labels: Project: V6 Launch
