### ISSUE TITLE
add InstanceDiscriminator to upgrade guide for callbacks

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1196] opened 2016-02-17 22:23 UTC
```
In order to use the callbacks feature you need to specify an endpoint instance ID via 
EndpointConfiguration.ScaleOut().InstanceDiscriminator(string discriminator)
```

related to https://github.com/Particular/NServiceBus.Callbacks/pull/10

**Comment by SimonCropp** [comment] 2016-02-17 22:25
@SzymonPobiega also it is unclear if the discriminator is required on the sender/receiver or both

**Comment by SzymonPobiega** [comment] 2016-02-18 06:32
@SimonCropp that thing will show when you add a callback package so I assumed people will understand where to add the discriminator. But the upgrade guide should specify it because it would be read without this context.

**Comment by SzymonPobiega** [comment] 2016-03-02 07:16
@SimonCropp does my comment make it more clear or you still think it should be fixed?

**Comment by weralabaj** [comment] 2016-03-02 14:29
@SzymonPobiega Not sure whether it was intended but in upgrade guide we have two sections related to callbacks: http://docs.particular.net/nservicebus/upgrades/5to6#handling-responses-on-the-client-side and http://docs.particular.net/nservicebus/upgrades/5to6#synchronous-request-response. Do we need both?

IMO that should be merged and I can do that once you clarify, thanks.

**Comment by SzymonPobiega** [comment] 2016-03-03 08:35
@weralabaj good catch! Here's the PR that attempts to merge these sections: https://github.com/Particular/docs.particular.net/pull/1246

**Closed** 2016-03-03 09:14 UTC
Labels: Tag: Core v6
