### ISSUE TITLE
Detail how to do a clean uninstall of ServiceControl

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#3483] opened 2017-12-04 09:07 UTC
based on https://github.com/Particular/docs.particular.net/issues/1340.

Detail what's left behind after an uninstall i.e queues, any empty directories and UrlAcls. Similar document to https://docs.particular.net/servicecontrol/installation only about uninstall.

Also, there is no entry in Window's programs & features menu for "ServiceControl", only the SC management tool. This can confuse users who want to uninstall/reinstall ServiceControl.

**Comment by weralabaj** [comment] 2018-05-07 09:04
@timbussmann I'm not sure what do you mean, is that related to doco menu? If so, can you please check if the issue is still relevant? The menu structure has been changed significantly since then.

**Comment by weralabaj** [comment] 2018-05-09 06:25
@Particular/servicecontrol-maintainers Please, have a look.

**Comment by SzymonPobiega** [comment] 2018-05-15 12:50
@weralabaj sounds reasonable but I am not sure how to prioritize this to be honest. I haven't heard any customer complaining about this.

**Comment by timbussmann** [comment] 2018-05-15 12:56
@SzymonPobiega I've opened this issue as it come up during a conversation with an user.

**Comment by weralabaj** [comment] 2018-05-28 09:09
ping, should I just copy the comment @mikeminutillo or do you plan on extending it?

**Comment by mikeminutillo** [comment] 2018-05-29 06:29
Created a PR for this. https://github.com/Particular/docs.particular.net/pull/3806

Look OK?

**Comment by danielmarbach** [comment] 2018-06-03 14:53
Closed via https://github.com/Particular/docs.particular.net/pull/3806

**Closed** 2018-06-03 14:52 UTC
