### ISSUE TITLE
Feedback: 'MSMQ Dead Letter Queue Custom Check'

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#3197] opened 2017-09-08 20:23 UTC
Feedback for 'MSMQ Dead Letter Queue Custom Check' https://docs.particular.net/samples/msmq/dlq-customcheck/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/msmq/dlq-customcheck/sample.md

ping @Particular/msmq-transport-maintainers 

Should this have a screenshot showing a failed custom check in ServicePulse?

**Comment by indualagarsamy** [comment] 2017-09-08 20:35
Thanks for the feedback @DavidBoike. I don't think a screen shot in ServicePulse will make it more better. It does include a related article to the Custom Checks. That should be sufficient. I don't see value in adding screenshots to this article. +1 to close this issue. cc / @Particular/msmq-transport-maintainers

**Comment by weralabaj** [comment] 2017-09-20 06:46
Duplicate of https://github.com/Particular/docs.particular.net/issues/3216

**Closed by weralabaj** 2017-09-20 06:46 UTC
