### ISSUE TITLE
High Availability across DC's & geographic distribution

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#261] opened 2014-03-26 13:43 UTC
This is probably only for the really big deployments, but a lot can be said (and done) about this type of application, where failover across DC's, or even across clouds is required. Same for systems that need to run in parallel across multiple geographic regions.

**Comment by mauroservienti** [comment] 2015-02-10 15:06
Is this somewhat related to #368?

**Comment by yvesgoeleven** [comment] 2015-02-10 15:18
yes, same thing really

**Comment by mauroservienti** [comment] 2015-02-10 15:23
closing as duplicate of #368

**Closed by mauroservienti** 2015-02-10 15:23 UTC
Labels: Azure, Concepts, Improvement
