### ISSUE TITLE
Feedback: Unit of Work - NServiceBus

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2483] opened 2017-02-27 17:37 UTC
Page: https://docs.particular.net/nservicebus/pipeline/unit-of-work

> In Version 6 IManageUnitsOfWork does not wrap the Outbox transaction.

Yes, I carefully read the article https://docs.particular.net/nservicebus/outbox/, but I still wonder what exactly the "Outbox transaction" is and which implications not wrapping it has.

Furthermore, in the article about the Outbox, why do you have to suppress the queue transaction for "Dispatch" and "Mark as dispatch"? These 2 are the last steps in the image, so you could simply complete the queue transaction before instead of suppressing it. If you just want to prevent sending be a part of the outer queue transaction, I have no idea, why you would want to do that.
Although I spent quite a lot of time on trying to fully understand the Outbox article, I did not get the transaction handling depicted in the image.

**Comment by indualagarsamy** [comment] 2017-02-27 19:45
@Niklas-Peter - Thank you for your feedback. Much appreciated. 

ping @Particular/nservicebus-maintainers - Can you please review the documentation and add more clarification to address @Niklas-Peter's questions?

**Comment by timbussmann** [comment] 2017-02-28 09:14
I agree with @Niklas-Peter , the statement about the outbox transaction is confusing. I tracked it down to the following issue: https://github.com/Particular/NServiceBus/issues/4134

so maybe something like
> In Version 6 IManageUnitsOfWork does not wrap the persistence transactions. The persistence transaction can therefore still fail after the unit of work completed.

thoughts? /cc @tmasternak (you wrote that note I think)

> Furthermore, in the article about the Outbox, why do you have to suppress the queue transaction for "Dispatch" and "Mark as dispatch"? These 2 are the last steps in the image, so you could simply complete the queue transaction before instead of suppressing it. 

if we would complete the queue transaction, the message is consumed. If then the dispatching fails, the consumed message will never be processed again and the outgoing messages are lost. With the wrapping transaction, if the suppressed dispatch fails, any exception will still cause the message to fail (the suppress is required to not cause a rollback of dispatched messages in case the incoming message can't be completed for whatever reason). Through retry mechanism, NServiceBus then tries to dispatch the stored outbox messages again. Does this explanation help you understand the outbox design?

**Comment by tmasternak** [comment] 2017-02-28 09:44
> In Version 6 IManageUnitsOfWork does not wrap the persistence transactions. The persistence transaction can therefore still fail after the unit of work completed.

@timbussmann I like it. From the user perspective the change in the behavior is that not all exceptions are visible in `IManageUnitsOfWork.End(Exception)`. 

>if we would complete the queue transaction, the message is consumed. If then the dispatching fails, the consumed message will never be processed again and the outgoing messages are lost. With the wrapping transaction, if the suppressed dispatch fails, any exception will still cause the message to fail (the suppress is required to not cause a rollback of dispatched messages in case the incoming message can't be completed for whatever reason). Through retry mechanism, NServiceBus then tries to dispatch the stored outbox messages again. Does this explanation help you understand the outbox design?

I think that the current [image](https://docs.particular.net/nservicebus/outbox/#how-it-works) in the doco is a legacy from V5. The reason why we used `Suppress Queue Tx.` vs. `Disptach Queue Tx.` is explicitly mentioned here is the fact that in V5 we had to suppress the receive transaction to prevent outgoing dispatches from enlisting into receive message which could result in escalation to DTC. That being said I think it should be changed for V6 doco and named `Dispatch Tx.`.

**Comment by Niklas-Peter** [comment] 2017-03-02 10:15
> if we would complete the queue transaction, the message is consumed. If then the dispatching fails, the consumed message will never be processed again and the outgoing messages are lost. With the wrapping transaction, if the suppressed dispatch fails, any exception will still cause the message to fail [...]. Through retry mechanism, NServiceBus then tries to dispatch the stored outbox messages again. 

@timbussmann Assumed, the handlers and the "Store recorded actions" were successful: Is the database transaction now committed independently from the receive transaction and the dispatching?
If the receive transaction is rolled back after committing the database transaction, the message will be retried. When receiving this message again, how do you prevent executing the business logic again while at the same time retrying the dispatching of the recorded actions?

> is the fact that in V5 we had to suppress the receive transaction to prevent outgoing dispatches from enlisting into receive message which could result in escalation to DTC.

@tmasternak Why is that not necessary anymore in V6?

**Comment by Niklas-Peter** [comment] 2017-03-02 11:01
> In Version 6 IManageUnitsOfWork does not wrap the persistence transactions. The persistence transaction can therefore still fail after the unit of work completed.

If in previous versions the persistence transaction was wrapped by the unit of work, how did you realize this:
> For example, committing NHibernate transactions, or calling SaveChanges on the RavenDB session.

Are the 2 sections in https://docs.particular.net/nservicebus/pipeline/unit-of-work mutually excluding alternatives for unit of works or will there always be a `TransactionScope` wrapping the unit of work whilst  `IManageUnitsOfWork` is just an optional callback for the application to do things right after the `TransactionScope` started respectively just before it ends? 

> The End() method is called when the processing is complete.
What exactly does that mean: After all handlers completed, but before any transaction (transport, persistence) was committed?

**Comment by tmasternak** [comment] 2017-03-02 12:26
> Assumed, the handlers and the "Store recorded actions" were successful: Is the database transaction now committed independently from the receive transaction and the dispatching?

This is correct.

> When receiving this message again, how do you prevent executing the business logic again while at the same time retrying the dispatching of the recorded actions?

Handler actions done in scope of db transactions, the outgoing messages and incoming messageId are stored in atomically. Thanks to that we can skip the handler processing part when we see the message with messageId second time and do the dispatch transaction only. If interested in the details [here](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageProcessingConnector.cs#L22) is the logic responsible for that.

> EDIT: What happens if dispatching fails again and again until the message is considered failed? Then the database transaction is committed, but the recorded actions will never complete and the initial message will be listed in ServicePulse.

The message can be retired from ServicePulse otherwise it's processing state is undetermined (as the processing can fail at any point).

> Why is that not necessary anymore in V6?

In V6 the recommended option to enable `Outbox` is to use [EnableOutbox](https://docs.particular.net/nservicebus/outbox/#enabling-the-outbox) extension method which switches transport transaction mode to [ReceiveOnly](https://docs.particular.net/nservicebus/transports/transactions#transactions-transport-transaction-receive-only). That prevents `Outbox` transaction from enlisting and that's why suppressing is not needed. I think that it also shows that `Suppress` part on the diagram is simply implementation detail.

**Comment by tmasternak** [comment] 2017-03-02 13:47
> > If in previous versions the persistence transaction was wrapped by the unit of work (i.e., the persistence transaction had ended when End() was called), how did you realize this:
>
>For example, committing NHibernate transactions, or calling SaveChanges on the RavenDB session.

I think that confusion comes from the `transaction` part here - it is inconsistently used in the doco. It refers to the `Db Tx.` on the [how it works](https://docs.particular.net/nservicebus/outbox/#how-it-works) page. What this statement means is that `Db Tx.` is committed after the `IManageUnitsOfWork.End` callback is called.

One of the ways to achieve `For example, committing ....` would be to have `IManageUnitsOfWork` implementation that would initialize e.g. RavenDb session in `Begin` and register it in the container with [InstancePerUnitOfWork](https://docs.particular.net/nservicebus/containers/#dependency-lifecycle-instanceperunitofwork) and flush it later in the `End`. Please note that in V6 there is a simpler way to achieve the same thing by using custom behavior approach. This [sample](https://docs.particular.net/samples/pipeline/unit-of-work/) shows details.

> Are the 2 sections in https://docs.particular.net/nservicebus/pipeline/unit-of-work mutually excluding alternatives for unit of works or will there always be a TransactionScope wrapping the unit of work whilst IManageUnitsOfWork is just an optional callback for the application to do things right after the TransactionScope started respectively just before it ends?

The 2 sections are not mutually exclusive. Using `IMangeUnitsOfWork` does not wrap handlers in `TransactionScope` and wrapping does not force user to register `IMangeUnitsOfWork`. It can be used on it's own and will be called after all handlers are invoked. Here is a [sample](https://docs.particular.net/samples/unit-of-work/) showing `IMangeUnitsOfWork` usage only.

**Comment by timbussmann** [comment] 2017-03-06 12:06
@tmasternak do you know how to update the image as you proposed?

**Comment by timbussmann** [comment] 2017-03-08 15:24
as #2519 is merged I think the feedback is addressed. I still like @tmasternak proposal to update the image, but I don't know whether there is some kind of editable file to regenerate the image, so I'll unassign myself and hand this back to @Particular/docs-maintainers.

**Comment by SimonCropp** [comment] 2017-03-09 04:04
the diagram has been updated by @mikeminutillo https://docs.particular.net/nservicebus/outbox/ https://github.com/Particular/docs.particular.net/pull/2530  it is now a visio file if anyone wants to edit it.

**Comment by Niklas-Peter** [comment] 2017-03-14 19:14
The updated diagram is much better.
@tmasternak @timbussmann 
Again, a question concerning

> In Version 6 IManageUnitsOfWork does not wrap the Outbox transaction.

This statement is only about `IManageUnitsOfWork`. What is about WrapHandlersInTransactionScope? Will this transaction scope wrap the Outbox transaction?

The primary motivation for the Outbox in the documentation is to avoid DTC. However, it requires to use the same database for everything. I want to use the Outbox for another reason: Get transaction guarantees for transports not supporting DTC. I can not use the same database for the Outbox and for my business data, but I accept escalating to DTC.

Hence, I wonder whether this works: Enable the Outbox and WrapHandlersInTransactionScope using a transport not supporting DTC (e.g., RabbitMQ). Now I assume, that all the database transactions (business and Outbox) enlist in the WrapHandlersInTransactionScope transaction scope. It would escalate to DTC, but I would get transaction guarantees for all resources involved (databases and transport).

**Comment by timbussmann** [comment] 2017-03-15 07:00
> What is about WrapHandlersInTransactionScope? Will this transaction scope wrap the Outbox transaction?

the transaction scope is opened on the `IIncomingPhysicalMessageContext` stage and therefore before the outbox transaction.

> I want to use the Outbox for another reason: Get transaction guarantees for transports not supporting DTC. 

This is exactly the use case the outbox was designed for.



>  It would escalate to DTC, but I would get transaction guarantees for all resources involved (databases and transport).

This is an interesting thought, but it's certainly no scenario we had in mind when designing the outbox. I think this is an invalid configuration as the outbox requires the outbox transaction to be commited before continuing, without the risk of being rolled back later due to failures on other enlisted transactions. 

In short, it is not possible to have the same transactional guarantees for something not enlisted with DTC. You will be able to address certain scenarios, but there will always be edge cases e.g. you will have the risk of the DTC completing successfully while the transport will fail and rollback. At this point, sent messages are already dispatched regardless. Or it will be possible for the DTC transaction to fail, while outgoing messages also were sent. Processing the incoming message again, would not deduplicate the message and send out the outgoing messages again.

Such a configuration makes it extremely hard to reason about the behavior of your system in edge cases. My recommendation is clearly to go with full DTC, the regular outbox approach or otherwise embrace the concept of duplicate messages and write idempotent message handlers.

**Comment by Niklas-Peter** [comment] 2017-03-15 19:06
@timbussmann 
> I think this is an invalid configuration as the outbox requires the outbox transaction to be committed before continuing, without the risk of being rolled back later due to failures on other enlisted transactions

What do you mean with "continuing"? What follows the outbox transaction? If I look at the outbox diagram, it seems as if the outbox transaction would wrap all handlers and was only followed by the dispatch phase. 

Does the UoW transaction scope wrap the outbox' dispatch phase? If _not_, I do not understand the problems you mentioned:

> risk of the DTC completing successfully while the transport will fail and rollback. At this point, sent messages are already dispatched regardless.

Then in my suggested combination of the outbox and the UoW transaction scope, the message will be retried and only the dispatching will be re-executed. If a message had already been dispatched, the receiver will deduplicate it.

 > Or it will be possible for the DTC transaction to fail, while outgoing messages also were sent. Processing the incoming message again, would not deduplicate the message and send out the outgoing messages again.

Assuming the UoW transaction scope completes before dispatching, this can not happen.

**Comment by timbussmann** [comment] 2017-03-17 06:54
> What do you mean with "continuing"? What follows the outbox transaction? If I look at the outbox diagram, it seems as if the outbox transaction would wrap all handlers and was only followed by the dispatch phase.

the diagramm contains the disatch + (even more importantly) the "mark as dispatched" tasks, which must not be rolled back (but could be if you enlist them with an ambient transaction).

> Does the UoW transaction scope wrap the outbox' dispatch phase?

You asked about starting an ambient transaction in `WrapHandlersInTransactionScope` which does wrap the outbox steps.

> Then in my suggested combination of the outbox and the UoW transaction scope, the message will be retried and only the dispatching will be re-executed. If a message had already been dispatched, the receiver will deduplicate it.

and what if the message will never successfully complete and go to the error queue? Messages are dispatched regardless.

It's very tricky to get these tangled transaction behavior right and while it seems that certain scenarios seem to work just fine, you'll end up with edge cases you were not thinking about to behave incorrectly, therefore I highly recommend to not follow that approach.

**Comment by timbussmann** [comment] 2017-03-30 06:50
I think we can close this one as the page has been updated to address the feedback. @Niklas-Peter feel free to reopen this issue in case you still see issues with that page. If you would like to discuss the outbox implementation further it might make sense to raise an issue in the NServiceBus repository directly.

**Closed by timbussmann** 2017-03-30 06:50 UTC

**Comment by Niklas-Peter** [comment] 2017-05-03 11:08
@timbussmann 

> the transaction scope is opened on the IIncomingPhysicalMessageContext stage and therefore before the outbox transaction.

[That](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageProcessingConnector.cs#L34) seems as if the Outbox transaction would be started before the IIncomingPhysicalMessage stage, does it not?

**Comment by timbussmann** [comment] 2017-05-03 16:02
@Niklas-Peter I lost quite a bit of context on this issue but your assumption on the order of the two behaviors seems to be correct.

Relating to the idea of using a DTC transaction for the outbox and the business data persistence, I think neither of the approaches would help:

* starting the transaction scope after the outbox transaction (current behavior) means that the outbox cannot participate in the DTC transaction.
* starting the transactionscope outside the `TransportReceiveToPhysicalMessageProcessingConnector` means that transactions could be rolled back although the outgoing messages have been dispatched.

I think it would be possible in general to support your scenario by the following steps:
1. receive incoming message
2. start transaction scope
3. start outbox storage transaction
4. invoke handlers (and use business data storage transactions)
5. commit transaction scope (commit outbox and business data storage before)
6. dispatch messages
7. mark messages as dispatched

this is currently not possible to implement using the existing pipeline extensibility API and the Outbox wasn't designed with that idea in mind, but it might be worth raising this as a feature request in the NSB repo? Thoughts @Niklas-Peter @SzymonPobiega

**Comment by timbussmann** [comment] 2017-05-04 08:23
@Niklas-Peter fyi: I raised an issue in NSB to discuss this feature request: https://github.com/Particular/NServiceBus/issues/4665
