### ISSUE TITLE
Create a sample on how to use NServiceBus in a Blazor app

### ISSUE THREAD

**Issue by lailabougria** [Particular/docs.particular.net#5735] opened 2022-06-02 07:21 UTC
As requested by one of our champs:

> Blazor server has full access to all the things server-side. 
> It would be a cool sample so see:
> - a button that triggers an NServiceBus message
> - the result of that handler/saga being routed back via messaging to that user (or /and other users)
> - see the UI update that "your task has completed  [link]"

POA

- [x] Learn Blazor- https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
- [x]  Identify the sample to mirror in Blazor- https://docs.particular.net/nservicebus/hosting/asp-net?version=extensions.hosting_2, which is a sample on how to host an nservicebus endpoint in an [asp.net](http://asp.net/) core application.
- [x] Create a sample using Blazor
- [x] Publish the sample
- [x] Announce

**Comment by TravisNickels** [comment] 2022-12-20 07:36
## 📝 Status update

### ✔ What has been done
- Draft PRs have been opened to update the DocsEngine and the docs.particular.net repos
- The Blazor sample has been created
- The documentation for the sample has been created



### ⚠ Risks


- The highlighting of c# syntax using highlight.js for snippets in `.razor` files does not work as intended for how we generate snippets in the DocsEngine.  Here are some of the options:
  - The `.razor` file snippet is displayed in our docs without highlighting for now.
  - The DocsEngine is modified to tag snippets inside of `.razor` files as cs or csharp files so that the cshtml-razor library does not even need to be used. (This is probably outside of the scope for this small task).

### 📅 What to expect


- Determine if the snippet in the `.razor` file can be highlighted properly?
  - If not, can the snippet be displayed in out docs without highlighting?
- Ready the draft PRs to be reviewed and merged

Next status update planned: 2022-12-22

- [x] The plan of action is up-to-date as of this status update

<sup>[guidelines](https://github.com/Particular/StaffSuccess/blob/master/guidelines/facilitation.md#providing-status-updates) version 2022-12-01</sup>

**Closed** 2023-01-25 22:12 UTC
Labels: Small Task
