### ISSUE TITLE
Feedback: 'NServiceBus Step-by-step: Getting Started'

### ISSUE THREAD

**Issue by gbiellem** [Particular/docs.particular.net#4427] opened 2019-07-09 00:38 UTC
Feedback for 'NServiceBus Step-by-step: Getting Started' https://docs.particular.net/tutorials/nservicebus-step-by-step/1-getting-started/

Regarding:

"In this tutorial we will always use .ConfigureAwait(false) when awaiting tasks in order to avoid capturing and restoring the SynchronizationContext."

I'm curious why this advice is being given.  The tutorial uses console apps which don't have a SynchronizationContext.

**Comment by timbussmann** [comment] 2019-07-10 08:32
Hey Greg!

We've had many discussions about usage of `ConfigureAwait(false)` in our samples and ended up with using it everywhere as a general rule. The main reason is that `ConfigureAwait(false)` can be considered a recommended best practice to avoid potential deadlocks and improve performance. We wanted to follow that best practice and raise awareness for it. 

You're right that technically `ConfigureAwait(false)` isn't necessary in handler code. We didn't want to make any assumptions that there will never be a context (as NServiceBus uses `ConfigureAwait(false)` everywhere internally, there is technically no guarantee that a handler might not be in a context depending on hosting, persistence and transport implementation). We felt that we either need to apply `ConfigureAwait(false)` consistently or not at all.

**Comment by SimonCropp** [comment] 2019-07-10 23:14
@timbussmann 

can u give a real world example of how a missing `ConfigureAwait(false)` can cause a deadlock in a console hosted NSB endpoint?

and do you have any numbers on the performance improvements by using  `ConfigureAwait(false)` in the context of NSB?

**Comment by gbiellem** [comment] 2019-07-10 23:17
Thanks for getting back to me Tim

t would be great if the rationale in your explanation was spelled out in the documentation. 

I quizzed some developers here as to what they thought the one liner meant before posting the feedback.and also why they were using ConfigureAwait(false) in their handler code.  Some had no idea and were just blindly following the advice, others assumed that NServiceBus must be using a SynchronizationContext internally and therefore also assumed it was always required.  

Without adding the rationale that one liner is pushing developers down the cargo cult programming route, which would seem to fly in the face of one of the key principles at Particular - "Make Developers Better".

**Comment by timbussmann** [comment] 2019-07-11 08:13
> can u give a real world example of how a missing ConfigureAwait(false) can cause a deadlock in a console hosted NSB endpoint?

I don't have any sample at hand for such a scenario. Usually, those deadlock scenarios aren't simple examples but are caused by deep chains of async code with some blocking code nested somewhere. This might be unlikely in the context of console applications but keep in mind that endpoints can be run in many hosts and handler code is easy to move between different hosts. Using `ConfigureAwait(false)` is just the general practice we're applying it consistently across our documentation and samples. 

We feel that it's the better tradeoff to point out the existence of ConfigureAwait to developers wo weren't aware of it before than ignoring it because it's not providing value in every case. Many best practices explicitly state that it's better to use ConfigureAwait(false) by default and opting out, rather than ignoring it (e.g. see other best practice recommendations in addition to the previously linked blog post: https://markheath.net/post/async-antipatterns https://gist.github.com/jonlabelle/841146854b23b305b50fa5542f84b20c ). We feel we make a bigger impact by showing how to write the safest async code but unfortunately the `ConfigureAwait` API is just not very clear and obvious.
We also try to help our users understand the best practices e.g. by providing blog posts or webinars like this one https://particular.net/webinars/async-await-best-practices.

However, I agree that the documentation seems to miss the arguments why we're using ConfigureAwait(false) everywhere and that might be something we could add to the existing resources.

Thoughts?

**Comment by gbiellem** [comment] 2019-07-11 09:00
> However, I agree that the documentation seems to miss the arguments why we're using ConfigureAwait(false) everywhere and that might be something we could add to the existing resources.

+100.   That's all I was asking for.  :)

**Comment by timbussmann** [comment] 2019-07-11 09:33
@gbiellem was there a specific doco section/page you were searching for more information about this (just trying to figure out the best place to add something so it's easy to find)?

**Comment by gbiellem** [comment] 2019-07-11 12:02
@timbussmann  This issue spawned out a discussion we had internally about ConfigureAwait and why it was being used in our projects even though none of them have a SynchronizationContext.  One of reasons given was that Particular were applying it in a blanket fashion to sample and advocating it's usage in the docs site.  I was trying to find where that assertion had come from and that line was what i found when searching and as I stated above I was curious what the reasoning behind it was.

**Comment by timbussmann** [comment] 2019-07-24 08:53
closing this after adding some related statement to the docs here: https://github.com/Particular/docs.particular.net/pull/4436

Thanks for the feedback Greg! 👍

**Closed by timbussmann** 2019-07-24 08:53 UTC

**Comment by gbiellem** [comment] 2019-07-24 09:53
Awesome.  Thanks for this @timbussmann
