### ISSUE TITLE
Feedback: 'Unit Testing NServiceBus'

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/docs.particular.net#3226] opened 2017-09-18 01:58 UTC
Feedback for 'Unit Testing NServiceBus' https://docs.particular.net/samples/unit-testing/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/unit-testing/sample.md

ping @Particular/nservicebus-maintainers 

There is no details about how to use `TestableEndpointInstance` in the doco. Originally raised in a StackOverflow question https://stackoverflow.com/questions/46226952/how-to-mock-out-iendpointinstance-of-nservicebus

**Comment by SimonCropp** [comment] 2017-09-18 22:59
duplicate of https://github.com/Particular/docs.particular.net/issues/3220

**Closed by SimonCropp** 2017-09-18 22:59 UTC

**Comment by mikeminutillo** [comment] 2017-09-19 01:59
Oops. Sorry. I normally check to see if an issue is a duplicate.
