### ISSUE TITLE
The scripting documentation for NHibernate.Persistence is inadequate

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/docs.particular.net#2474] opened 2017-02-24 21:52 UTC
The current documentation we have for scripting the SQL for NHibernate is
https://docs.particular.net/nservicebus/nhibernate/scripting

It lacks a proper introduction, it also lacks all the other needed scripting such as creating the tables necessary for Persistence for timeouts, subscription, gateway, etc. 

Relates to: https://github.com/Particular/docs.particular.net/issues/2473

**Comment by indualagarsamy** [comment] 2017-02-24 21:52
ping @Particular/nhibernate-persistence-maintainers

**Comment by weralabaj** [comment] 2017-03-02 08:24
Related issue https://github.com/Particular/docs.particular.net/issues/1046

ping @Particular/nhibernate-persistence-maintainers can you take care of it under maintainers budget?

**Comment by MarcinHoppe** [comment] 2017-03-02 08:56
I am aware of it and plan to handle it. Given the current cardinality of @Particular/nhibernate-persistence-maintainers I encourage you not to expect wonders in terms of timeliness 😞.

**Comment by MarcinHoppe** [comment] 2017-03-06 14:32
@Particular/docs-maintainers Can we close this as a duplicate of #1046 and get together a TF for #1046?

The issues can be the other way around, just recognizing a duplicate.

**Comment by weralabaj** [comment] 2017-03-06 14:48
sure

**Closed by weralabaj** 2017-03-06 14:48 UTC
