### ISSUE TITLE
Add information on how to migrate subscription and timeout data

### ISSUE THREAD

**Issue by HEskandari** [Particular/docs.particular.net#2780] opened 2017-05-25 06:40 UTC
In certain scenarios, users want to migrate subscription and timeout data from one machine/instance to another. The main blocker is that the addresses include the machine name and are hard-coded in the subscription data in the database.

The goal of this issue would be explaining how to update addresses in the Timeout Manager's table.

 - [ ] NHibernate persister
 - [ ] SQL persister

**Comment by weralabaj** [comment] 2017-05-25 09:30
Is that for a specific package or in general?

**Comment by SzymonPobiega** [comment] 2017-05-25 10:27
@weralabaj RavenDB already has this: https://docs.particular.net/nservicebus/ravendb/reroute-existing-timeouts. Ideally we should have this for each persister. Realistically, we should have it for NH and SQL

**Comment by SzymonPobiega** [comment] 2017-05-25 12:53
I looked at the RavenDB doco and it seems to be quite painful to actually migrate the timeout data. The problem is, some headers also needs to be changed so it means json manipulation in the SQL query. Quite brittle :-(

**Comment by weralabaj** [comment] 2017-10-06 10:32
@HEskandari Since this issue has not been addressed for such a long time, I propose to close it. We can reopen if we get support cases related to that problem or any customers express interest in getting that kind of guidance.

**Closed by weralabaj** 2017-10-06 10:32 UTC
