### ISSUE TITLE
Feedback: 'Recoverability'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#4104] opened 2018-11-02 21:24 UTC
Feedback for 'Recoverability' https://docs.particular.net/nservicebus/recoverability/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/recoverability/index.md

> Depending on the concurrency and transactionality settings of the endpoint immediate retries might happen even if configured to be off. To ensure that no retries is performed the endpoints needs to be configured to be either non transactional or the concurrency restricted to 1.

When is this possible? How setting concurrency to more than 1 will affect immediate retries? Very confusing note that is missing details.

**Comment by SeanFeldman** [comment] 2018-11-06 23:45
@Particular/nservicebus-maintainers can you shed some light on this? Thank you.

**Comment by andreasohlund** [comment] 2018-11-07 07:56
I have a faint memory that v4 was exposed to some concurrency issues when "counting" the immediate retries in memory since the increment happened after the message was rolled back to the queue. 

Looking at the current transport seam design I don't think this is an issue, eg. the learning transport increments the count before rolling back

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs#L280

So does Rabbit - https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.Transport.RabbitMQ/Receiving/MessagePump.cs#L253

But I wonder with eg. Rabbit/ASB/ASQ what happens when message handling take to long, if you have concurrency > 1 the message will be visible in the queue again and will be reprocessed without the retry count being incremented?

**Comment by bording** [comment] 2018-11-07 15:47
> But I wonder with eg. Rabbit/ASB/ASQ what happens when message handling take to long, if you have concurrency > 1 the message will be visible in the queue again and will be reprocessed without the retry count being incremented?

That won't be a problem for Rabbit since it doesn't have any sort of visibility timeout.

**Comment by andreasohlund** [comment] 2018-11-08 07:38
>The Immediate Retry mechanism is implemented by making the message available for consumption again at the top of the queue, so that the endpoint can process it again without any delay. Immediate Retries cannot be used when transport transactions are disabled.

@bording this is not correct for RabbitMQ right? (it does them inmemory)

**Comment by andreasohlund** [comment] 2018-11-08 08:14
I think the summary is: You can never be 100% sure that the message won't be reprocessed since some transports (eg. RabbitMQ) will potentially requeue messages even in transaction mode `none`. 

Unless we see that a as bug and fix rabbitmq?

**Comment by bording** [comment] 2018-11-08 15:31
> @bording this is not correct for RabbitMQ right? (it does them inmemory)

Correct. SQS does the same thing. Seems like we shouldn't be trying to go into implementation-specific details here on the page.

**Comment by bording** [comment] 2018-11-08 15:31
> Unless we see that a as bug and fix rabbitmq?

Not a bug and not really fixable.

**Comment by andreasohlund** [comment] 2018-11-12 07:36
I think we need to give the page an overhaul and perhaps state something like "you can never be 100% sure that handlers won't be invoked multiple times so you need to add some own locking if you can't afford messages being reprocessed" ?

And also remove mentioning of concurrency etc

**Comment by tmasternak** [comment] 2018-12-07 08:30
AFIK the only statement that is true for all transport implementations in the context of immediate retries is:

> If the configuration says do x immediate retries we will do at least x and do our best not to do much more.

BTW the whole concurrency setting discussion assumes no competing consumers.

**Comment by danielmarbach** [comment] 2020-02-24 11:11
@andreasohlund @tmasternak @SeanFeldman do you guys want to finish this off by polishing the sentence a bit and then close this? Or no longer relevant?

**Comment by SeanFeldman** [comment] 2020-02-24 19:04
Absolutely. Except I don't know of a scenario when immediate retried would take place despite being disabled. In the PR @tmasternak has raised there's still no mentioning of the edge cases that could cause this behaviour.

**Comment by ramonsmits** [comment] 2020-04-29 17:43
Merged https://github.com/Particular/docs.particular.net/pull/4708 , closing

**Closed by ramonsmits** 2020-04-29 17:43 UTC
