### ISSUE TITLE
Feedback: 'Message Identity'

### ISSUE THREAD

**Issue by serge-portima** [Particular/docs.particular.net#6222] opened 2023-09-26 09:10 UTC
Feedback for 'Message Identity' https://docs.particular.net/nservicebus/messaging/message-identity

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/message-identity.md

According to my tests and this SO answer, this is simply not true: https://stackoverflow.com/a/77173544/15097703

**Comment by kbaley** [comment] 2023-09-29 19:10
@serge-portima I tried to reproduce the scenario [from the SO answer here](https://github.com/kbaley/asb-message-id-test) with a simple NSB command. When I peeked at the message in the portal, both the message ID and the correlation ID had been modified to `moo`.

So if you don't mind, let's dive into some details because my sample is very much simplified. Are you able to modify the sample to reproduce the behaviour you're seeing? If not, can you provide some details on your environment so I can try to figure out what's going on? Specifically, the version of NServiceBus, and the ASB transport as well as any special configuration.

**Comment by kbaley** [comment] 2023-10-04 17:34
@serge-portima 

`CustomizeNativeMessage` works on the native ASB message, not on the NServiceBus message. So the message ID you set here doesn't affect the NServiceBus message ID.

Are you able to provide a sample for your scenario where `SetMessageId` doesn't work?

**Comment by serge-portima** [comment] 2023-10-05 06:33
@kbaley it was not working when the code was:

`        var sendOptions = new SendOptions();
        sendOptions.RouteToThisEndpoint();
        
        if (command is not IMessage message)
        {
            return MessageSession.Send(command, sendOptions, cancellationToken);
        }

        sendOptions.SetMessageId(message.MessageId);`

**Comment by kbaley** [comment] 2023-10-05 14:22
@serge-portima I tested with my sample (in the `send-local` branch) and I'm still not able to reproduce the issue. But a couple of things jumped out at me in your snippet:

- You need an `await` for `MessageSession.Send` (unless you intended to return the task itself)
- You're setting the message ID after returning the task/sending the message

**Comment by serge-portima** [comment] 2023-10-05 14:27
@kbaley I omit the last part for brevity. I really have no idea what else could be specific to my setup. If I find anything, I'll share it here.

**Comment by SeanFeldman** [comment] 2023-10-06 03:35
@serge-portima, create a repro and share as a GitHub repo.

**Comment by kbaley** [comment] 2023-10-09 13:00
@serge-portima I'm going to close this for now as it seems to be working as intended. It's possible we need to include a caveat along the lines of "in this case, `SetMessageId` won't work for these reasons". If you're able to send a reproduction of the issue, post it here and we'll re-open the issue.

**Closed by kbaley** 2023-10-09 13:00 UTC
