### ISSUE TITLE
Add license installation docs for SC and SP

### ISSUE THREAD

**Issue by adamralph** [Particular/docs.particular.net#2382] opened 2017-01-17 08:22 UTC
*from https://github.com/Particular/OptimizeTrialExtensions/issues/127#issuecomment-272943415*

SI has [a page about license installation](https://docs.particular.net/serviceinsight/license) but SC and SP have none. Should they?

/cc @Particular/servicecontrol-maintainers

**Comment by WilliamBZA** [comment] 2017-01-17 08:36
Duplicate of https://github.com/Particular/docs.particular.net/issues/2381? Do we really need 2 issues for this?

**Comment by adamralph** [comment] 2017-01-17 08:44
@WilliamBZA we can align the top level menu items (as described in #2381) without adding license installation docs for SC and SP.

**Comment by WilliamBZA** [comment] 2017-01-17 08:49
I think the first step should be to decide if it even makes sense to align the top level menu items. Off the top of my head, this issue needs a bit more though though as SP doesn't _actually_ have a license file so does it make sense to have a license installation doc?

I would prefer some thought going into #2381 first before opening smaller issues to action work that may not be necessary.

Can we rather close this one pending some thought and decision of the more general #2381 and then potentially re-open this one once we have some consensus?

**Comment by adamralph** [comment] 2017-01-17 09:05
For me the two issues are orthogonal, but if the preference is to combine them then I don't mind.

**Comment by gbiellem** [comment] 2017-01-17 23:31
ServiceControl already has a licensing docs page -> https://docs.particular.net/servicecontrol/license

**Comment by mikeminutillo** [comment] 2017-01-19 07:19
This gets a bit complicated with SC/SP. 

ServiceControl is not officially covered by our [licensing policy](https://particular.net/licensing) and ServicePulse is effectively an HTML/JS app which does not rely on a license file. Despite that, SC will not start without a valid license file and SP must be connected to a running SC instance in order to be of any use. In effect, the license file installed into SC *is* the SP license. 

This is one of the arguments for merging SC and SP.

**Comment by gbiellem** [comment] 2017-01-23 07:39
@mikeminutillo the website is being updated to reflect the fact that SC is part of the licensing - See https://github.com/Particular/Website.Frontend/issues/480

**Comment by weralabaj** [comment] 2017-03-02 07:39
@adamralph  since #2381 was closed and we decided not to align the structure for now, what should we do with this issue? is this still relevant? also see updated licensing info on our website https://particular.net/licensing

**Comment by adamralph** [comment] 2017-03-02 20:46
@weralabaj I'm content with @Particular/servicecontrol-maintainers @Particular/servicepulse-maintainers and @Particular/docs-maintainers making a decision on this.

**Comment by gbiellem** [comment] 2017-03-02 23:27
I'm going to close it.  Reopen it if you disagree

**Closed by gbiellem** 2017-03-02 23:27 UTC

**Comment by sergioc** [comment] 2017-03-03 09:07
In any case, it's already [documented for SC](https://docs.particular.net/servicecontrol/license), so it's only missing the article for SP.

**Comment by sergioc** [comment] 2017-03-03 09:31
I've also done some improvements to https://docs.particular.net/servicepulse/installation in https://github.com/Particular/docs.particular.net/pull/2511
